package io.github.ranolp.bachmeer.util

object Symbols {
    val tick = "✔"
    val cross = "✖"
    val star = "★"
    val square = "▇"
    val squareSmall = "◻"
    val squareSmallFilled = "◼"
    val play = "▶"
    val circle = "◯"
    val circleFilled = "◉"
    val circleDotted = "◌"
    val circleDouble = "◎"
    val circleCircle = "ⓞ"
    val circleCross = "ⓧ"
    val circlePipe = "Ⓘ"
    val circleQuestionMark = "?⃝"
    val bullet = "●"
    val dot = "․"
    val line = "─"
    val ellipsis = "…"
    val pointer = "❯"
    val pointerSmall = "›"
    val info = "ℹ"
    val warning = "⚠"
    val hamburger = "☰"
    val heart = "♥"
    val arrowUp = "↑"
    val arrowDown = "↓"
    val arrowLeft = "←"
    val arrowRight = "→"
    val radioOn = "◉"
    val radioOff = "◯"
    val checkboxOn = "☒"
    val checkboxOff = "☐"
    val checkboxCircleOn = "ⓧ"
    val checkboxCircleOff = "Ⓘ"
    val questionMarkPrefix = "?⃝"
}
